### ISSUE TITLE
Error when setting "prescribe_landcover" : "landcoverfpc"

### ISSUE THREAD

**Issue by deniseruijsch** [PIK-LPJmL/LPJmL#48]
I am currently working with LPJmL 5 (5.9.7) and I encounter an issue when attempting to run the model using a prescribed landcover input instead of dynamic natural vegetation. The run fails with the following error:

ERROR244: Unknown PFT "Tropical C4 grass" in map 'landcovermap'.

The same error appears for other PFTs, including "Temperate C3 grass" and "Polar C3 grass," but not for tree PFTs.

Steps to Reproduce:
Modify the LPJmL configuration to run the model with a prescribed landcover map instead of dynamic natural vegetation.
Add the landcover input file in the input.cjson file. 
Keep the mapping section in the configuration file unchanged (see screenshots in the attached files).
Run the model and observe the errors.

Error Trace:
Upon tracing the error, I found that it points to the following file in the source code:
/src/lpj/fscanlandcovermap.c

Could you clarify why the landcover map inputs for "Tropical C4 grass," "Temperate C3 grass," and "Polar C3 grass" trigger this error? Is there another configuration setting that I might need to adjust to resolve this issue?

Any guidance or suggestions would be greatly appreciated!

![Image](https://github.com/user-attachments/assets/ee77e1d8-f245-4fa3-92e5-678397ff89eb)
![Image](https://github.com/user-attachments/assets/3d7d9c70-9cad-449b-a937-23dcaa63787e)

**Comment by sostberg** [comment]
Thanks for bringing this to our attention. We can reproduce the issue. 

The cause of the error is that [line 76](https://github.com/PIK-LPJmL/LPJmL/blob/master/src/lpj/fscanlandcovermap.c#L76) in `fscanlandcovermap.c` only checks against the first 8 PFTs in the PFT list, which does not include the grasses.
This is because `nnat` is incorrect.  `nnat` is determined in [line 33](https://github.com/PIK-LPJmL/LPJmL/blob/master/src/lpj/fscanlandcovermap.c#L33) as `nnat=getnnat(npft,config);`

However, if you check the call of `fscanlandcover()` in [`fscanconfig()`](https://github.com/PIK-LPJmL/LPJmL/blob/master/src/lpj/fscanconfig.c#L905) the passed `npft` is already limited to the natural PFTs, i.e. `getnnat()` is called twice.

Try changing [line 905] in fscanconfig.c to
```
    config->landcovermap=fscanlandcovermap(file,&config->landcovermap_size,"landcovermap",config->npft[GRASS]+config->npft[TREE],config);
```
This should fix the issue.

**Comment by deniseruijsch** [comment]
Thank you for the quick response! 
I changed the line 905, but unfortunately I still get the same error:

`ERROR244: Unknown PFT "Tropical C4 grass" in map 'landcovermap'.`

**Comment by sostberg** [comment]
Did you recompile the code after the change?

**Comment by deniseruijsch** [comment]
I saved the new file, but I am not sure what "recompiling" means. Could you explain how I can recompile the code?

**Comment by sostberg** [comment]
You need to run `make all` after any changes to the source code.

**Comment by sostberg** [comment]
Closing this issue as SOLVED. Reopen if the problem persists.
